name: Run PyTest
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3
     
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
       
    - name: Install PyQt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0
       
    - name: Test with pytest
      run: |
        # Run tests with Xvfb for GUI testing
        xvfb-run --auto-servernum pytest --cov=./ --cov-report=xml
       
    - name: Upload test coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
       
    - name: Generate HTML test report
      if: always()  # Run even if tests fail
      run: |
        pip install pytest-html
        mkdir -p test-reports
        xvfb-run --auto-servernum pytest --html=test-reports/pytest-report.html --self-contained-html
       
    - name: Upload test report
      if: always()  # Run even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: test-reports/